### PR TITLE
Development with Vagrant

### PR DESCRIPTION
**Pull request by mertonium**
**PR Context:** I wanted to have a local version of citygram to hack on, but I was having problems getting postgis setup without messing up my work dev environments...so I used vagrant to sandbox this app.  I offer up this PR so that others in my position can get up and running with a minimal amount of hassle. 

Codewise, the only changes are the addition of the Vagrantfile, a slightly modified Procfile named Procfile.vagrant and an update to the .ruby-version file (which I see is already part of #159 ).

The bulk of this PR is a new section in the README that goes over setting up the vagrant box for the first time.  I'm not a linux expert, so there may be better ways to setup the box - I just made it work:tm:. The instructions are essentially my notes from getting the app running locally.

### CODE REVIEW

**Comment by dirkkelly** [comment]
This looks great, vagrant will save us a lot of startup time with newcomers.

I think it would be good to look at automating the vagrant box setup though, this can be done using provision scripts, example below.

**Vagrantfile**

```
...

config.vm.provision "shell", path: "vagrant/setup.sh"
config.vm.provision "shell", path: "vagrant/start.sh", run: :always
```

**vagrant/setup.sh**

```
#!/bin/bash

sudo apt-get -y update
sudo apt-get -y install build-essential zlib1g-dev libssl-dev libreadline-dev libyaml-dev libcurl4-openssl-dev curl git-core python-software-properties libxslt1-dev libxml2-dev libmysqlclient-dev libsqlite3-dev libpq-dev nodejs redis-server 

...
```

**vagrant/start.sh**

```
#!/bin/bash

cd /vagrant
bundle exec foreman start -f Procfile.vagrant

**Comment by mertonium** [comment]
@dirkkelly - It's like your inside my head! I just realized this was possible this morning. I will update the PR asap.

**Comment by bigfleet** [comment]
@mertonium @dirkkelly I would love to merge this in, guys, but I'm not going to do it unless you write yourselves up as Vagrant maintainers.  I am not a habitual user and don't know its ins and outs.

**Comment by dirkkelly** [comment]
@bigfleet @mertonium Personally Typically I shy away from Vagrant development of Ruby apps, I've enjoyed successes with it for PHP projects but find it more of an inconvenience than Rbenv. 

I appreciate the importance of simple to boot development environments though, especially when it comes to encouraging new users.

@mertonium if you can create those setup and startup scripts I'll give this branch a go locally and see how it performs, in the event that I can use it, I will work with you as a a Vagrant maintainer for this project.

**Comment by bigfleet** [comment]
If commitment isn't appropriate, I would welcome contributions to the project Wiki, as that allows for maintenance by those who are not necessarily ongoing contributors.

**Comment by mertonium** [comment]
Hey y'all - sorry I let this slide off my radar. I've been updating this vagrant branch with provisioning scripts, but it's taking longer than expected.

Wrt maintenance: I'm down for helping out, my hesitation is that I don't use Vagrant day to day, so I'm definitely not an expert.

I'm going to see if I can wrap this branch up soon and update the README so instead of a ~80 lines of Vagrant talk it's ~10-20 lines with @dirkkelly 's and my handles at the bottom. Then y'all can take a look and let me know what you think.

**Comment by dirkkelly** [comment]
@mertonium cool, I'll be happy to check this out.

**Comment by bcipolli** [comment]
I'm a new developer looking to work with citygram; I'd be happy to try this out. @mertonium can you rebase to the latest master?

**Comment by bigfleet** [comment]
See also #249

**Comment by jszwedko** [comment]
I think this is superseded by #249

**Pull request closed without merging**
