### PR TITLE
simple Procfile, Heroku compatibly ensured.

### PR DESCRIPTION
**Pull request by dirkkelly**
There's no benefit from having multiple Procfiles, Heroku will only run web by default and a site administrator can scale the rest appropriately. In development everything will start automatically.

screen shot 2015-02-28 at 5 03 29 pm

### CODE REVIEW

**Comment by invisiblefunnel** [comment]
Procfile.dev is for development environments. Redis doesn't need to be declared in the Procfile used by Heroku. Redis is an addon attached via an environment variable on Heroku.

**Comment by dirkkelly** [comment]
@invisiblefunnel absolutely understand, however having a Procfile.dev breaks default behavior, meaning that any developer who is used to using foreman needs to run an alternative command.

An alternative approach which doesn't break default behavior is described in the wiki https://github.com/ddollar/foreman/wiki/Environment-specific-Behavior

**Comment by bigfleet** [comment]
I had a little head-desk moment personally when reading this one.  The crucial idea is this:

> Redis server shouldn't be declared in the Procfile used by Heroku.

This is a trade-off between preventing the operator from doing something harmful and making development smoother by eliminating another concept for the developer to be aware of.

In this case, the operator is happy to accept the responsibility not to scale up redis on Heroku.

That said, I don't want the dependence on /usr/local in Procfile-- bring a slimmed down redis.conf into config and we'll use it from there.  If that guidance isn't clear, @dirkkelly,  throw me the ball and I'll dunk it.

**Comment by bigfleet** [comment]
To be clear, my headdesk moment was about "Why do I have all these Procfile.dev files in all my repos?"  Many devs are unfamiliar with foreman and everything that can be done to minimize the cognitive load of development is worth strong consideration.

**Comment by dirkkelly** [comment]
@bigfleet updated to use a local redis config, I stripped out all comments and blank lines. Did the same with newrelic config for consistency.

**Comment by bigfleet** [comment]
@dirkkelly I added a little sugar on top to keep from the /usr filesystem dependency, and now available on master.

**Comment by dirkkelly** [comment]
thanks @bigfleet!

**Pull request merged**
