### PR TITLE
Add Triangle Region 

### PR DESCRIPTION
**Pull request by nigelterry**
Changed configuration and added background image (We are working on getting a better image before we go to full visible status).

We have our first data set ready to go. Here is the incantation for it. I wasn't sure how you wanted to receive it:

Publisher.create! do |pub|
  pub.title = "Crime Reports"
  pub.endpoint = "http://citygram.codeforcary.org/crime-reports"
  pub.active = true
  pub.visible = false
  pub.city = "Triangle NC"
  pub.icon = "police-incidents.png"
  pub.state = "NC"
  pub.description = "Crime Reports from local Police Departments"
  pub.tags = ["triangle-nc"]
end

Please let me know when we can test. Thanks

### CODE REVIEW

**Comment by bigfleet** [comment]
@nigelterry I've queued up the datasource, and we'll see how it runs!  If everything goes according to plan, I should be able to bring you up in the next 24-48 hours.

**Comment by bigfleet** [comment]
@nigelterry Pardon me, only saw your note about the image on re-reading.  The data pull has generated some thousand items.  I can review locally with this background image.

Soft launches are very common for Citygram so just let me know when you'd like this deployed.

**Comment by nigelterry** [comment]
I guess my next question is, how can we test this out without going fully live?

**Comment by bigfleet** [comment]
@nigelterry I've been collecting data from that endpoint since Aug. 18 and have 5583 events.  So the data collection part is already going well.

Testing the appearance is possible on any development machine.  There is no staging/QA environment for Citygram.  Cities do not appear in the dropdown if they don't have an active publisher, though, so since there's only one to start for RTP area, I can quickly turn it off and on from my seat.

As far as I know, this ticket is holding on final adaptation of the background image and how to get attribution reflected.  Is that still the case?

**Comment by nigelterry** [comment]
@bigfleet We don't have an instance of citygram running. I think we can go with the current image for now. We have a brigade meeting this evening, and it would be great if the Triangle was turned on at least for that period.

**Pull request merged**
