### PR TITLE
ENH: add San Diego location & background.

### PR DESCRIPTION
**Pull request by bcipolli**
Ready to go live with the San Diego code enforcements! 

Please use the following snippet to update the database (taken from the ["going live"](https://github.com/codeforamerica/citygram/wiki/Going-Live) doc.

We'd love to get this in before the new year, so we can add this to our brigade's accomplishments for the year. Right @merelyanode :)

```postgres
Publisher.create! do |pub|
  pub.title = "Code Violations"
  pub.endpoint = "https://sd-notifications.herokuapp.com/dsd/code-enforcement"
  pub.active = true
  pub.visible = true
  pub.city = "San Diego"
  pub.icon = "code-violations.png"
  pub.state = "CA"
  pub.description = "Current information about complaints received that have become cases for further investigation."
  pub.tags = ["san-diego"]
end
```

### CODE REVIEW

**Comment by bcipolli** [comment]
Any chance we can get some feedback on this? Thanks!

**Comment by bcipolli** [comment]
Still hoping to get some feedback on this; we'd love to have this merged before the new year. It's a major accomplishment for our brigade that we'd like to share with our supporters. Thanks!

**Comment by bigfleet** [comment]
@bcipolli Working on it now, and if everything looks good, it'll go live in <60m.

**Comment by bcipolli** [comment]
Awesome, thanks @bigfleet !! @merelyanode @MrMaksimize this was merged, hopefully we'll be live shortly--stay tuned!

**Comment by bigfleet** [comment]
@bcipolli We have a timeout on the middleware layer, which is expiring.  Any way you can cache your response for 10 minutes (or longer?)

**Comment by bcipolli** [comment]
I've seen that before, the first response in a while can be slow (but the second much quicker). I can look into caching.

**Comment by bigfleet** [comment]
@bcipolli That one went right through!  A few more minutes and it'll be up.

**Comment by bcipolli** [comment]
Great! I think it's on the back-end city API, they probably cache to some middleware that expires after a while. 

I've opened an issue to deal with this (https://github.com/opensandiego/open-dsd-notifications/issues/12), but sounds like this is usable for the time being! Which is great, I've got some pressing work things I'd prefer to work on first :)

**Comment by bigfleet** [comment]
@bcipolli 137 events have been processed for this feed, and [they appear in the interface](https://www.citygram.org/san-diego)  Congratulations, and welcome to Citygram.

**Comment by bcipolli** [comment]
YEAH!!! :+1: Thanks @bigfleet !

**Comment by bcipolli** [comment]
@bigfleet I tried subscribing to San Diego, then Miami. Not sure if this is related to what just changed: https://github.com/codeforamerica/citygram/issues/237

**Pull request merged**
